---
build_from:
  aarch64: "ghcr.io/linuxserver/healthchecks:3.3.20240603"
  amd64: "ghcr.io/linuxserver/healthchecks:3.3.20240603"
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: healthchecks"
  org.opencontainers.image.url: https://github.com/bluemaex/home-assistant-addons
  org.opencontainers.image.source: https://github.com/bluemaex/home-assistant-addons/healthchecks
  org.opencontainers.image.documentation: https://github.com/bluemaex/home-assistant-addons/healthchecks/README.md
  org.opencontainers.image.created: "2024-05-16T18:56:46Z"
  org.opencontainers.image.revision: 9d30b2cc720ca8f996ce226fb8025f18f8bb703e
  org.opencontainers.image.version: 3.1.1
