---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.24"
  amd64: "ghcr.io/home-assistant/amd64-base:3.24"
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: openbao"
  org.opencontainers.image.url: https://github.com/bluemaex/home-assistant-addons
  org.opencontainers.image.source: https://github.com/bluemaex/home-assistant-addons/openbao
  org.opencontainers.image.documentation: https://github.com/bluemaex/home-assistant-addons/openbao/README.md
  org.opencontainers.image.created: "2026-08-22T22:16:16Z"
  org.opencontainers.image.revision: ceee55b2adbd612bd62a6b965d2065eef7d13829
  org.opencontainers.image.version: 0.1.2
