---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: openbao"
  org.opencontainers.image.url: https://github.com/bluemaex/home-assistant-addons
  org.opencontainers.image.source: https://github.com/bluemaex/home-assistant-addons/openbao
  org.opencontainers.image.documentation: https://github.com/bluemaex/home-assistant-addons/openbao/README.md
  org.opencontainers.image.created: "2026-03-06T22:00:22Z"
  org.opencontainers.image.revision: 7694e2bdb93b2659cc58fb15c2aa96fb75dc3380
  org.opencontainers.image.version: 1.0.0
