---
name: OpenBao
version: 1.0.0
slug: openbao
description: |
  OpenBao is an identity-based secrets and encryption management system.
arch:
  - aarch64
  - amd64
image: "ghcr.io/bluemaex/ha-addons-openbao-{arch}"
startup: system
url: https://github.com/bluemaex/home-assistant-addons/tree/master/openbao
init: false
ports:
  8200/tcp: 8200
ports_description:
  8200/tcp: OpenBao API and UI
map:
  - data
  - ssl
options:
  log_level: info
  auto_unseal: true
  tls_disable: true
  env_vars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  auto_unseal: bool
  tls_disable: bool
  env_vars:
    - str
