---
build_from:
  i386: "ghcr.io/home-assistant/i386-base:3.20"
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
  armv7: "ghcr.io/home-assistant/armv7-base:3.20"
codenotary:
  signer: homeassistant@blmx.de
  base_image: notary@home-assistant.io
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: 'Home Assistant Unofficial Add-on: victoriametrics'
  org.opencontainers.image.url: https://github.com/bluemaex/home-assistant-addons
  org.opencontainers.image.source: https://github.com/bluemaex/home-assistant-addons/victoriametrics
  org.opencontainers.image.documentation: https://github.com/bluemaex/home-assistant-addons/victoriametrics/README.md
  org.opencontainers.image.created: "2024-05-16T18:52:50Z"
  org.opencontainers.image.revision: 1731d29a8a39463a482a15ecc80dc33ebe947a21
  org.opencontainers.image.version: 2.0.5
