---
build_from:
  aarch64: "ghcr.io/linuxserver/syslog-ng:4.8.3"
  amd64: "ghcr.io/linuxserver/syslog-ng:4.8.3"
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: syslog-ng"
  org.opencontainers.image.url: https://github.com/bluemaex/home-assistant-addons
  org.opencontainers.image.source: https://github.com/bluemaex/home-assistant-addons/syslog-ng
  org.opencontainers.image.documentation: https://github.com/bluemaex/home-assistant-addons/syslog-ng/README.md
  org.opencontainers.image.created: "2024-10-13T15:15:32Z"
  org.opencontainers.image.revision: f9eb503a4f2f9ad780df9c24bdcf33205646e151
  org.opencontainers.image.version: 5.0.4
