---
build_from:
  aarch64: "ghcr.io/linuxserver/syslog-ng:4.5.0"
  amd64: "ghcr.io/linuxserver/syslog-ng:4.5.0"
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: syslog-ng"
  org.opencontainers.image.url: https://github.com/bluemaex/home-assistant-addons
  org.opencontainers.image.source: https://github.com/bluemaex/home-assistant-addons/syslog-ng
  org.opencontainers.image.documentation: https://github.com/bluemaex/home-assistant-addons/syslog-ng/README.md
  org.opencontainers.image.created: "2024-03-10T19:20:54Z"
  org.opencontainers.image.revision: 7480b06fdb73b9ac9ea871709f33d1b3f15b8301
  org.opencontainers.image.version: 5.0.3
