---
auth_enabled: false

analytics:
  reporting_enabled: false

server: {}

common:
  path_prefix: /data/loki
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1

schema_config:
  configs:
    - from: 2025-06-21
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /data/loki/tsdb-chunks

compactor:
  working_directory: /data/loki/tsdb-shipper-compactor
  retention_enabled: true
  delete_request_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: ${RETENTION_PERIOD:29d}
