---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.24"
  amd64: "ghcr.io/home-assistant/amd64-base:3.24"
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: unpoller"
  org.opencontainers.image.url: https://github.com/bluemaex/home-assistant-addons
  org.opencontainers.image.source: https://github.com/bluemaex/home-assistant-addons/unpoller
  org.opencontainers.image.documentation: https://github.com/bluemaex/home-assistant-addons/unpoller/README.md
  org.opencontainers.image.created: "2026-08-18T20:08:15Z"
  org.opencontainers.image.revision: 4c30f153f7635247d8eac92c81ec474357eb4db9
  org.opencontainers.image.version: 5.0.1
